# Generated by Django 5.1 on 2024-09-05 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course_name', models.CharField(max_length=100, null=True)),
                ('Duration', models.CharField(max_length=100, null=True)),
                ('fees', models.CharField(max_length=100, null=True)),
                ('Instructor', models.CharField(max_length=100, null=True)),
                ('description', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
