# Generated by Django 5.1 on 2024-09-07 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('std', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100, null=True)),
                ('Email', models.EmailField(max_length=254, null=True)),
                ('Phone', models.CharField(max_length=100, null=True)),
                ('Subject_Taught', models.CharField(max_length=100, null=True)),
                ('Grade_Level', models.CharField(max_length=100, null=True)),
                ('Years_of_Experirnce', models.CharField(max_length=100, null=True)),
                ('Additional_Information', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
