# Generated by Django 5.1 on 2024-09-07 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('std', '0002_tbl_teachers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_teachers',
            old_name='Years_of_Experirnce',
            new_name='Years_of_Experience',
        ),
    ]
