# Generated by Django 5.1 on 2024-09-10 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('std', '0004_tbl_application_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_application_form',
            name='terms',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
