# Generated by Django 5.1 on 2024-09-11 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('std', '0006_remove_tbl_application_form_select_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_application_form',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='std.tbl_courses'),
        ),
    ]
